title: of Experiment and Result
author: Oksigenasu
email: oksigenasu@yahoo.com
description: > # this means to ignore newlines until "show_exerpts:"
  My development website.  i'll do my best to keep it posted.  About hardware making and software development
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture
exclude: [vendor]
future: true
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Zeta DeGray
  tagline: Maker, Hardware and Software Enthusiast
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: notsigenasu
    github:  oksigenasu
    linkedIn: in/oksigenasu
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
